### ISSUE TITLE
Missing data in view's

### ISSUE THREAD

**Issue by stephenpaulbrown** [jimmyatSplunk/TA-bigfix#1]
configuration.xml and inputs.xml are both empty other than calling the base.html template. I receive the following error when navigating to them " An error occurred while reading the page template...." The only data written to the web_service.log is similar to "INFO [5a60399ca07ff1ac66c910] view:1053 - bypass module system fast path". I thought this error was being caused by a conflict with another app but i installed this on TA on an indexer and still received the same error.

**Comment by jimmyatSplunk** [comment]
What version of Splunk did you install this on?

I had started development on 7.0 and upgraded to 7.1 which I probably shouldn't have done.

**Comment by jimmyatSplunk** [comment]
I've gone back to the latest version of 6.6 and found the add-on loads without issue.

**Comment by stephenpaulbrown** [comment]
7.2, and then i upgraded to 7.2.1 this morning

**Comment by stephenpaulbrown** [comment]
i will spin up a new box with version 7.0 and try it again and troubleshoot what changed and how to fix it. I will keep you updated with my progress

**Comment by stephenpaulbrown** [comment]
im still getting the same error on version 7.0.3... in your /default/nav/ui/views/ both the inputs.xml and configuration.xml just references the base.html template. Is that how you intended the app to work or do you have updated xml files not included in this repository?

**Comment by jimmyatSplunk** [comment]
The app was built using the Splunk Add-on Builder and those are created by the app. Out of curiosity, did you rename the parent directory from “TA-bigfix-master” to “TA-bigfix”? It’s likely the hard-coding of the app doesn’t play well with GitHub downloads.

--
Jimmy Maple
Professional Services Consultant - Public Sector
Mobile: 760-390-9924

**Comment by stephenpaulbrown** [comment]
looks like it is on my end. i pulled the TA down in a zip format and instead of unpacking it and moving it over via winscp to my app folder i just uploaded it like it was a tar ball... let me unzip the files and move them over manually and restart and see.

**Comment by stephenpaulbrown** [comment]
the directory is still named TA-bigfix-master. and after moving the files over manually, i am still having the same issue. i will continue to troubleshoot on my end to see what is going on. It very well could be just something on my end

**Comment by jimmyatSplunk** [comment]
You will need to change the name to “TA-bigfix”. That should fix it.

--
Jimmy Maple
Professional Services Consultant - Public Sector
Mobile: 760-390-9924

**Comment by stephenpaulbrown** [comment]
That worked, thank you sir.
