### ISSUE TITLE
Unable to initialize modular input "bigfix users" defined in the app "TA-bigfix-master": Introspecting scheme=bigfix users

### ISSUE THREAD

**Issue by Aniketkg** [jimmyatSplunk/TA-bigfix#4]
Hi ,

Got below given issue after install of Add-on
Unable to initialize modular input "bigfix users" defined in the app "TA-bigfix-master": Introspecting scheme=bigfix users

I have installed on stand-alone Splunk server.
Please help.
Thanks
Aniket

**Comment by jimmyatSplunk** [comment]
When downloading the add-on from GitHub, you need to remove "master" suffix from the parent directory. "TA-bigfix-master" should become "TA-bigfix". This is due to hard-coding done when creating the app using the add-on builder.

**Comment by Aniketkg** [comment]
Thank you so much. Its working now
