### ISSUE TITLE
Cloud Vetting Failed

### ISSUE THREAD

**Issue by idunnogit** [jimmyatSplunk/TA-bigfix#9]
When I submitted a ticket to Cloud Support to install this TA on my Search Head I received the following report back. Can these issues be fixed so this can be installed on the Cloud?

<< Auto-Generated FAILED vetting comment:

[Cloud Vetting][Liverpool] #Custom 3.0.2 - TA-bigfix
Review fails vetting and cannot be installed.

This is a preliminary report. More issues may be found upon further review.
Thank you for your app install request. Your app did not meet security and functionality requirements for Splunk Cloud for the following reasons:

*[The application can be configured for unencrypted communication, which is not permitted in Splunk Cloud. All communication must be encrypted (HTTPS preferred).]
*User is able to configure url with http scheme which is not allowed on cloud. All calls must go with https. There is no validation available in python code File: bin/TA_bigfix_rh_settings.py Line Number: 30
*Change the version attribute in the root node of your Simple XML dashboard default/data/ui/views/assets.xml to <version=1.1>. Earlier dashboard versions introduce security vulnerabilities into your apps and are not permitted in Splunk Cloud File: default/data/ui/views/assets.xml Line Number: null

Once these issues are remedied you can resubmit your app for review.

In addition the following changes are recommended:
null

Alternatives:
null
>>

**Comment by jimmyatSplunk** [comment]
I apologize for not getting to this sooner. 

It should be noted that the TA itself should not be installed in its entirety in Splunk Cloud as many of the components are not required for the TA to function in Cloud.

That said, there are extractions in the TA that are applicable to search. Uploading this TA will require the removal of the components responsible for running the modular inputs as you can't configure them in Splunk Cloud.

I will work on packaging a Splunk Cloud compatible release.

**Comment by jimmyatSplunk** [comment]
The latest release is cleared for Splunk Cloud.
